name = "comidas-gratis"
type = "webpack"
account_id = "2b683141b95aa57904fdc9c6fffcad78"
workers_dev = true
route = ""
zone_id = "e2b45dfade2fd889f949e8821f047f4e"

[site]
bucket = "./public"
entry-point = "workers-site"
